version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vacancy-container
    image: vacancy_docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "5004:8000"
    tty: true
    stdin_open: true
    environment:
      DEBUG: "1"
